apiVersion: v1
kind: Service
metadata:
  name: platform-operations
  labels:
    app: platform-operations
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: platform-operations