---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-management
  labels:
    app: customer-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-management
  template:
    metadata:
      labels:
        app: customer-management
    spec:
      containers:
        - name: customer-management
          image: username/customer-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxi-driver-management
  labels:
    app: taxi-driver-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taxi-driver-management
  template:
    metadata:
      labels:
        app: taxi-driver-management
    spec:
      containers:
        - name: taxi-driver-management
          image: username/taxi-driver-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-operations
  labels:
    app: platform-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-operations
  template:
    metadata:
      labels:
        app: platform-operations
    spec:
      containers:
        - name: platform-operations
          image: username/platform-operations:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: map-data-provider
  labels:
    app: map-data-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: map-data-provider
  template:
    metadata:
      labels:
        app: map-data-provider
    spec:
      containers:
        - name: map-data-provider
          image: username/map-data-provider:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: customer-management
  labels:
    app: customer-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customer-management


---


apiVersion: v1
kind: Service
metadata:
  name: taxi-driver-management
  labels:
    app: taxi-driver-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxi-driver-management


---


apiVersion: v1
kind: Service
metadata:
  name: platform-operations
  labels:
    app: platform-operations
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: platform-operations


---


apiVersion: v1
kind: Service
metadata:
  name: map-data-provider
  labels:
    app: map-data-provider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: map-data-provider

