apiVersion: v1
kind: Service
metadata:
  name: taxi-driver-management
  labels:
    app: taxi-driver-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: taxi-driver-management