name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./customer-management/pom.xml
          mvn clean package -f ./taxi-driver-management/pom.xml
          mvn clean package -f ./platform-operations/pom.xml
          mvn clean package -f ./map-data-provider/pom.xml

      - name: Docker Build and push for CustomerManagement
        uses: docker/build-push-action@v4
        with:
          context: ./customer-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer-management:latest
            ghcr.io/${{ github.repository }}/customer-management:${{ github.ref_name }}
            
      - name: Docker Build and push for TaxiDriverManagement
        uses: docker/build-push-action@v4
        with:
          context: ./taxi-driver-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/taxi-driver-management:latest
            ghcr.io/${{ github.repository }}/taxi-driver-management:${{ github.ref_name }}
            
      - name: Docker Build and push for PlatformOperations
        uses: docker/build-push-action@v4
        with:
          context: ./platform-operations
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/platform-operations:latest
            ghcr.io/${{ github.repository }}/platform-operations:${{ github.ref_name }}
            
      - name: Docker Build and push for MapDataProvider
        uses: docker/build-push-action@v4
        with:
          context: ./map-data-provider
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/map-data-provider:latest
            ghcr.io/${{ github.repository }}/map-data-provider:${{ github.ref_name }}
            
